import {CertificateWrapperModel} from "../../../modules/health-certificate/CertificateWrapper.model";
import {DocumentModel} from "../../../models/Document.model";
import {DocumentTypeEnum} from "../../../models/DocumentType.enum";

export const mapCertificateWrapperToDocumentModel = (certificateWrapper: CertificateWrapperModel) => {
  return {
    //id will be generated by DB
    id: "",
    content : certificateWrapper,
    type: DocumentTypeEnum.HEALTHCERTIFICATE,
  } as DocumentModel;
}
